__bytes__ on the Buffer returning non-bytes
__bytes__ on the Buffer object is sometimes returning a bytearray instead of bytes.

Traceback (most recent call last):
  File "C:\Users\ddeason\PycharmProjects\opcua_test\venv\lib\site-packages\asyncua\client\ua_client.py", line 88, in _process_received_data
    data = bytes(buf)
TypeError: __bytes__ returned non-bytes (type bytearray)