fix ClientNonce and/or peer_certificate may be None
The ClientNonce and also the peer_certificate can be set to None,
this fixes the resulting TypeError

```
Traceback (most recent call last):
  File "...\Python312-32\Lib\site-packages\asyncua\server\uaprocessor.py", line 147, in process_message
    return await self._process_message(typeid, requesthdr, seqhdr, body)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\Python312-32\Lib\site-packages\asyncua\server\uaprocessor.py", line 213, in _process_message
    data = self._connection.security_policy.peer_certificate + params.ClientNonce
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
TypeError: can't concat NoneType to bytes
       ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
```

fixes #1821