[ Security ] Password encoding bug and typing adjustement
String are immutable, therefore the password is never encoded and it
throws this error when it's a string:

```
...../cryptography/hazmat/backends/openssl/backend.py in _load_key(self, openssl_read_func, convert_func, data, password)
   1284         userdata = self._ffi.new("CRYPTOGRAPHY_PASSWORD_DATA *")
   1285         if password is not None:
-> 1286             utils._check_byteslike("password", password)
   1287             password_ptr = self._ffi.from_buffer(password)
   1288             userdata.password = password_ptr

...../cryptography/utils.py in _check_byteslike(name, value)
     36         memoryview(value)
     37     except TypeError:
---> 38         raise TypeError("{} must be bytes-like".format(name))
     39
     40

TypeError: password must be bytes-like
```

This patch fixes this as well as some typing inaccuracy introduced by #281