With py3.10, high level asyncio API can't specify the event_loop argument anymore.
Consequently, When using thread dedicated to run the event_.loop, we now need to instantiate object like asyncio.Lock within the thread. However, the event loop can't be running before creating these objects as `loop.run_for_ever()` must be the background running thread process. Therefore, we can't have "get_running_loop()" calls in object constructors (like HaClient) when used with executors.

Before
```
In [15]: def get_t():
    ...:     loop = asyncio.new_event_loop()
    ...:     t = T()
    ...:     loop.run_for_ever()

In [16]: class T:
    ...:     def __init__(self, loop):
    ...:         asyncio.set_event_loop(loop)
    ...:         asyncio.get_running_loop()
    ...:         self.l = asyncio.Lock()
    ...:         print("Lock created")
    ...:

In [17]: t = Thread(target=get_t);t.start()

Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 932, in _bootstrap_inner
In [41]:     self.run()
  File "/usr/local//lib/python3.10/threading.py", line 870, in run
In [41]:     self._target(*self._args, **self._kwargs)
  File "<ipython-input-32-c4a1ea4cfdac>", line 3, in get_t
  File "<ipython-input-39-ebeae10dd173>", line 4, in __init__
RuntimeError: no running event loop
```
After

```
In [15]: def get_t():
    ...:     loop = asyncio.new_event_loop()
    ...:     t = T()
    ...:     loop.run_for_ever()

In [16]: class T:
    ...:     def __init__(self, loop):
    ...:         asyncio.set_event_loop(loop)
    ...:         self.l = asyncio.Lock()
    ...:         print("Lock created")
    ...:

In [17]: t = Thread(target=get_t);t.start()

Lock created

```