Fix uals -l asyncio error (#366)
* uals -l option fix

uals -l option conversion to async was incomplete and failed with error
TypeError: 'coroutine' object is not iterable.

* Fix obsolete server-example.py reference and remove unused _logger